### ISSUE TITLE
MonacoEnvironment declared more than once

### ISSUE THREAD

**Issue by alsoicode** [cisstech/nge#1]
After installing the @cisstech/nge package and its dependency, monaco-editor, I added the module to my app.module and child module.

I implemented the nge-monaco-editor component and when I run the application via `ng serve`, I receive the following error:

```bash
Error: node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:12:9 - error TS2451: Cannot redeclare block-scoped variable 'MonacoEnvironment'.

12     let MonacoEnvironment: Environment | undefined;
           ~~~~~~~~~~~~~~~~~

  node_modules/monaco-editor/monaco.d.ts:11:13
    11 declare let MonacoEnvironment: monaco.Environment | undefined;
                   ~~~~~~~~~~~~~~~~~
    'MonacoEnvironment' was also declared here.


Error: node_modules/monaco-editor/monaco.d.ts:11:13 - error TS2451: Cannot redeclare block-scoped variable 'MonacoEnvironment'.

11 declare let MonacoEnvironment: monaco.Environment | undefined;
               ~~~~~~~~~~~~~~~~~

  node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:12:9
    12     let MonacoEnvironment: Environment | undefined;
               ~~~~~~~~~~~~~~~~~
    'MonacoEnvironment' was also declared here.
```

**Comment by mciissee** [comment]
Can you share at least the following informations to allow me to test and reproduce the bug please :

- Angular version
- monaco-editor version
- @cisstech/nge version
- if possible parts of your code involving monaco-editor or nge-monaco-editor (modules, import statements, components...)

**Comment by mciissee** [comment]
Try to install the same version of monaco-editor as the one used by **nge** i.e. `0.31.1` because the lib [explicitly exports](https://github.com/cisstech/nge/blob/2f1eba59dfd2c5390d45b2b48622ffe8c02c7622/projects/nge/monaco/index.ts#L2) the typing file for monaco-editor so there may be a version conflict .

Thank you for reporting the error on the doc I have updated it!

**Comment by alsoicode** [comment]
I can verify that using `monaco-editor@0.30.1` does work as expected.

There's another bug in the sample code however...

The `ready` event emitter is of type `monaco.editor.IEditor`, but your `onCreateEditor` method expects to receive `monaco.editor.IStandaloneCodeEditor`
