### ISSUE TITLE
Outdated documentation for nge-monaco

### ISSUE THREAD

**Issue by TheDelta** [cisstech/nge#2]
Currently evaluating nge-monaco and noticed outdated install instructions on Usage (https://cisstech.github.io/nge/docs/nge-monaco/usage)

There seems to be no package `nge-monaco` and the whole repo must be used (`@cisstech/nge`)

Installation page (https://cisstech.github.io/nge/docs/nge-monaco/installation) seems to use outdated version as well 

Currently I use `npm i @cisstech/nge monaco-editor@0.31.1` (instead of 0.30.1)

I also noticed the code blocks use `U+00a0` which makes it hard to copy & paste the install instructions or example code.
(in the shell the spaces are omitted, at least on windows) and vscode complains (although easy to fix if a formatter is used - hopefully standard for everyone^^)

Also the link to the Editor Options is outdated, this seems to be the correct new one: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IEditorOptions.html

**Comment by mciissee** [comment]
@TheDelta Thanks for reporting this error, the documentation has been updated. Sorry for the delay, I was on vacation :)
